# Generated by Django 6.0.7 on 2026-08-03 10:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance_score', models.FloatField(help_text='Model-computed compatibility score for this pairing, 0.0-1.0.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_study_session', to='matching.match')),
            ],
            options={
                'db_table': 'group_study_session',
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matching.groupstudysession')),
            ],
            options={
                'db_table': 'feedback',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'session'), name='uq_feedback_student_session')],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='matching.match')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_participant',
                'constraints': [models.UniqueConstraint(fields=('match', 'student'), name='uq_matchparticipant_match_student')],
            },
        ),
    ]
